/* =========================================================================
   KPC Diagnostic - CHEMISTRY Question Bank (SERVER SIDE ONLY)
   SEC / MATSEC O-Level Chemistry. 10 topics x 4 = 40 (1 foundation,
   2 standard, 1 hard each). Calculation-heavy (mole / Mr / titration /
   energetics), plus concept MCQs and a few lenient typed answers.
   Original SEC-style content; publicQuestions() hides answers.
   ========================================================================= */
import { publicQuestions as pub, gradeAndReport as grade } from "./_grade.js";

export const SUBJECT = "Chemistry";

export const TOPIC_ORDER = [
  "Atomic Structure & Periodic Table",
  "Bonding & Structure",
  "The Mole & Stoichiometry",
  "Acids, Bases & Salts",
  "Rates of Reaction",
  "Energetics",
  "Redox & Electrolysis",
  "Metals & Reactivity",
  "Organic Chemistry",
  "Air, Water, Earth & Analysis"
];

export const QUESTIONS = [
  /* T1 Atomic Structure & Periodic Table */
  { topic:"Atomic Structure & Periodic Table", ref:"KPC Chemistry - Atomic Structure & Periodic Table", product:"chemistry-atomic",
    difficulty:"foundation", type:"work",
    q:"An atom has 11 protons and 12 neutrons. What is its mass number?",
    data:"Give a whole number.", accept:[23], unit:"",
    steps:`Mass number = number of protons + number of neutrons = 11 + 12<br><span class="final">Mass number = 23</span>` },
  { topic:"Atomic Structure & Periodic Table", ref:"KPC Chemistry - Atomic Structure & Periodic Table", product:"chemistry-atomic",
    difficulty:"standard", type:"mcq",
    q:"Elements in the same GROUP of the periodic table have the same number of...",
    opts:["protons","electrons in their outer shell","neutrons","occupied shells"], correct:1,
    steps:`Elements in the same group have the same number of <b>outer-shell electrons</b>, which is why they react in similar ways.<br><span class="final">Answer: electrons in their outer shell</span>` },
  { topic:"Atomic Structure & Periodic Table", ref:"KPC Chemistry - Atomic Structure & Periodic Table", product:"chemistry-atomic",
    difficulty:"standard", type:"work",
    q:"A sodium atom has 11 electrons, arranged 2, 8, 1. How many electrons are in its outer shell?",
    data:"Give a whole number.", accept:[1], unit:"",
    steps:`The arrangement is 2, 8, <b>1</b>, so the outer (third) shell holds 1 electron. This is why sodium is in Group 1.<br><span class="final">Answer: 1</span>` },
  { topic:"Atomic Structure & Periodic Table", ref:"KPC Chemistry - Atomic Structure & Periodic Table", product:"chemistry-atomic",
    difficulty:"hard", type:"mcq",
    q:"Going DOWN Group 1 (the alkali metals, lithium to potassium and beyond), the elements become...",
    opts:["less reactive","more reactive","non-metals","gases"], correct:1,
    steps:`Down Group 1 the outer electron is further from the nucleus and more easily lost, so the metals get <b>more reactive</b>.<br><span class="final">Answer: more reactive</span>` },

  /* T2 Bonding & Structure */
  { topic:"Bonding & Structure", ref:"KPC Chemistry - Bonding & Structure", product:"chemistry-bonding",
    difficulty:"foundation", type:"mcq",
    q:"A chemical bond formed by sharing pairs of electrons between non-metal atoms is called a...",
    opts:["ionic bond","covalent bond","metallic bond","nuclear bond"], correct:1,
    steps:`Sharing electrons between non-metals is <b>covalent</b> bonding. Transferring electrons (metal to non-metal) is ionic bonding.<br><span class="final">Answer: covalent bond</span>` },
  { topic:"Bonding & Structure", ref:"KPC Chemistry - Bonding & Structure", product:"chemistry-bonding",
    difficulty:"standard", type:"mcq",
    q:"Sodium chloride has a very high melting point. This is mainly because...",
    opts:["it is a simple molecule","there are strong forces in a giant ionic lattice","it contains weak hydrogen bonds","it is a metal"], correct:1,
    steps:`Sodium chloride is a <b>giant ionic lattice</b>; lots of strong electrostatic forces between oppositely charged ions must be broken, so the melting point is high.<br><span class="final">Answer: strong forces in a giant ionic lattice</span>` },
  { topic:"Bonding & Structure", ref:"KPC Chemistry - Bonding & Structure", product:"chemistry-bonding",
    difficulty:"standard", type:"text",
    q:"What type of bonding holds the particles together in a metal? (one word)",
    data:"Type your answer (a word).", accept:["metallic","metallic bonding"],
    steps:`Metals are held together by <b>metallic</b> bonding: a lattice of positive ions in a sea of delocalised (free) electrons.<br><span class="final">Answer: Metallic</span>` },
  { topic:"Bonding & Structure", ref:"KPC Chemistry - Bonding & Structure", product:"chemistry-bonding",
    difficulty:"hard", type:"mcq",
    q:"Graphite conducts electricity but diamond does not, even though both are made only of carbon. Why?",
    opts:["Graphite contains metal atoms","Graphite has free (delocalised) electrons; diamond has none","Diamond is a liquid","Graphite is an ionic compound"], correct:1,
    steps:`In graphite each carbon bonds to only three others, leaving one <b>delocalised electron</b> per atom that can carry charge. In diamond every electron is used in bonding, so it cannot conduct.<br><span class="final">Answer: Graphite has free electrons; diamond has none</span>` },

  /* T3 The Mole & Stoichiometry */
  { topic:"The Mole & Stoichiometry", ref:"KPC Chemistry - The Mole & Stoichiometry", product:"chemistry-mole",
    difficulty:"foundation", type:"work",
    q:"Calculate the relative formula mass (Mr) of water, H2O. (Ar: H = 1, O = 16)",
    data:"Give a number.", accept:[18], unit:"",
    steps:`Mr = (2 x 1) + 16 = 2 + 16<br><span class="final">Mr of H2O = 18</span>` },
  { topic:"The Mole & Stoichiometry", ref:"KPC Chemistry - The Mole & Stoichiometry", product:"chemistry-mole",
    difficulty:"standard", type:"work",
    q:"Calculate the relative formula mass (Mr) of calcium carbonate, CaCO3. (Ar: Ca = 40, C = 12, O = 16)",
    data:"Give a number.", accept:[100], unit:"",
    steps:`Mr = 40 + 12 + (3 x 16) = 40 + 12 + 48<br><span class="final">Mr of CaCO3 = 100</span>` },
  { topic:"The Mole & Stoichiometry", ref:"KPC Chemistry - The Mole & Stoichiometry", product:"chemistry-mole",
    difficulty:"standard", type:"work",
    q:"How many moles are there in 80 g of sodium hydroxide, NaOH? (Mr of NaOH = 40)",
    data:"Give your answer in moles (mol).", accept:[2], unit:"mol",
    steps:`moles = mass / Mr = 80 / 40<br><span class="final">= 2 mol</span>` },
  { topic:"The Mole & Stoichiometry", ref:"KPC Chemistry - The Mole & Stoichiometry", product:"chemistry-mole",
    difficulty:"hard", type:"work",
    q:"On heating, calcium carbonate decomposes: CaCO3 -> CaO + CO2. Calculate the mass of calcium oxide (CaO) formed from 50 g of calcium carbonate. (Mr: CaCO3 = 100, CaO = 56)",
    data:"Give your answer in grams (g).", accept:[28], unit:"g",
    steps:`moles CaCO3 = 50 / 100 = 0.5 mol.<br>The ratio CaCO3 : CaO is 1 : 1, so moles CaO = 0.5 mol.<br>mass = moles x Mr = 0.5 x 56<br><span class="final">= 28 g</span>` },

  /* T4 Acids, Bases & Salts */
  { topic:"Acids, Bases & Salts", ref:"KPC Chemistry - Acids, Bases & Salts", product:"chemistry-acids",
    difficulty:"foundation", type:"mcq",
    q:"Which pH value shows a strongly ACIDIC solution?",
    opts:["pH 1","pH 7","pH 9","pH 14"], correct:0,
    steps:`Acids have a low pH; the lower the number, the stronger the acid. pH 7 is neutral and above 7 is alkaline.<br><span class="final">Answer: pH 1</span>` },
  { topic:"Acids, Bases & Salts", ref:"KPC Chemistry - Acids, Bases & Salts", product:"chemistry-acids",
    difficulty:"standard", type:"text",
    q:"Name the gas produced when a reactive metal such as magnesium reacts with hydrochloric acid. (one word)",
    data:"Type your answer (a word).", accept:["hydrogen"],
    steps:`Metal + acid -> salt + <b>hydrogen</b>. The hydrogen gas gives a squeaky pop with a lit splint.<br><span class="final">Answer: Hydrogen</span>` },
  { topic:"Acids, Bases & Salts", ref:"KPC Chemistry - Acids, Bases & Salts", product:"chemistry-acids",
    difficulty:"standard", type:"mcq",
    q:"Which type of substance neutralises an acid to form a salt and water?",
    opts:["another acid","a base (alkali)","a salt","a fuel"], correct:1,
    steps:`A <b>base</b> (a soluble base is an alkali) neutralises an acid: acid + base -> salt + water.<br><span class="final">Answer: a base (alkali)</span>` },
  { topic:"Acids, Bases & Salts", ref:"KPC Chemistry - Acids, Bases & Salts", product:"chemistry-acids",
    difficulty:"hard", type:"work",
    q:"In a titration, 25.0 cm3 of sodium hydroxide is exactly neutralised by 20.0 cm3 of 0.10 mol/dm3 hydrochloric acid. The reaction is 1 : 1. Calculate the concentration of the sodium hydroxide.",
    data:"Give your answer in mol/dm3.", accept:[0.08], unit:"mol/dm³",
    steps:`moles HCl = concentration x volume = 0.10 x (20.0 / 1000) = 0.002 mol.<br>Ratio is 1 : 1, so moles NaOH = 0.002 mol.<br>concentration = moles / volume = 0.002 / (25.0 / 1000) = 0.002 / 0.025<br><span class="final">= 0.08 mol/dm3</span>` },

  /* T5 Rates of Reaction */
  { topic:"Rates of Reaction", ref:"KPC Chemistry - Rates of Reaction", product:"chemistry-rates",
    difficulty:"foundation", type:"mcq",
    q:"Increasing the temperature of a reaction usually does what to the rate of reaction?",
    opts:["increases it","decreases it","stops it","has no effect"], correct:0,
    steps:`Higher temperature gives particles more energy, so they collide more often and with enough energy to react. The rate <b>increases</b>.<br><span class="final">Answer: increases it</span>` },
  { topic:"Rates of Reaction", ref:"KPC Chemistry - Rates of Reaction", product:"chemistry-rates",
    difficulty:"standard", type:"mcq",
    q:"Which change would make marble chips react FASTER with hydrochloric acid?",
    opts:["using larger lumps of marble","grinding the marble into a powder","cooling the acid","using more dilute acid"], correct:1,
    steps:`Powdering the marble gives a much larger <b>surface area</b>, so there are more frequent collisions and a faster rate.<br><span class="final">Answer: grinding the marble into a powder</span>` },
  { topic:"Rates of Reaction", ref:"KPC Chemistry - Rates of Reaction", product:"chemistry-rates",
    difficulty:"standard", type:"mcq",
    q:"A catalyst speeds up a reaction. What happens to the catalyst by the end of the reaction?",
    opts:["It is used up","It is unchanged and can be reused","It turns into a gas","It becomes the product"], correct:1,
    steps:`A catalyst lowers the activation energy but is <b>not used up</b>, so the same catalyst can be used again.<br><span class="final">Answer: It is unchanged and can be reused</span>` },
  { topic:"Rates of Reaction", ref:"KPC Chemistry - Rates of Reaction", product:"chemistry-rates",
    difficulty:"hard", type:"mcq",
    q:"Increasing the concentration of a reactant increases the rate of reaction. The best explanation is that there are...",
    opts:["fewer particles in the same volume","more particles in the same volume, so more frequent collisions","particles with less energy","weaker bonds in the reactants"], correct:1,
    steps:`A higher concentration packs <b>more particles into the same volume</b>, so collisions happen more often and the rate goes up.<br><span class="final">Answer: more particles in the same volume, so more frequent collisions</span>` },

  /* T6 Energetics */
  { topic:"Energetics", ref:"KPC Chemistry - Energetics", product:"chemistry-energetics",
    difficulty:"foundation", type:"mcq",
    q:"A reaction that releases heat to the surroundings (the temperature rises) is described as...",
    opts:["exothermic","endothermic","neutral","catalytic"], correct:0,
    steps:`Releasing heat (temperature rises) is <b>exothermic</b>. Taking in heat (temperature falls) is endothermic.<br><span class="final">Answer: exothermic</span>` },
  { topic:"Energetics", ref:"KPC Chemistry - Energetics", product:"chemistry-energetics",
    difficulty:"standard", type:"mcq",
    q:"During an ENDOthermic reaction, what happens to the temperature of the surroundings?",
    opts:["it rises","it falls","it stays the same","it doubles"], correct:1,
    steps:`An endothermic reaction takes in heat from the surroundings, so the surroundings <b>cool down</b> (temperature falls).<br><span class="final">Answer: it falls</span>` },
  { topic:"Energetics", ref:"KPC Chemistry - Energetics", product:"chemistry-energetics",
    difficulty:"standard", type:"work",
    q:"In a calorimetry experiment, burning a fuel raises the temperature of 100 g of water by 20 degrees C. Calculate the heat energy gained by the water. (specific heat capacity of water = 4.2 J/g degrees C)",
    data:"Give your answer in joules (J).", accept:[8400], unit:"J",
    steps:`Q = m x c x change in temperature = 100 x 4.2 x 20<br><span class="final">= 8400 J</span>` },
  { topic:"Energetics", ref:"KPC Chemistry - Energetics", product:"chemistry-energetics",
    difficulty:"hard", type:"mcq",
    q:"During a reaction, which statement about bonds and energy is correct?",
    opts:["Breaking bonds releases energy; making bonds takes in energy","Breaking bonds takes in energy; making bonds releases energy","Both breaking and making bonds release energy","Bonds have nothing to do with energy"], correct:1,
    steps:`Breaking bonds <b>takes in</b> energy (endothermic step); making new bonds <b>releases</b> energy (exothermic step). The overall reaction is exothermic if more energy is released than taken in.<br><span class="final">Answer: Breaking bonds takes in energy; making bonds releases energy</span>` },

  /* T7 Redox & Electrolysis */
  { topic:"Redox & Electrolysis", ref:"KPC Chemistry - Redox & Electrolysis", product:"chemistry-redox",
    difficulty:"foundation", type:"mcq",
    q:"Oxidation can be defined as the...",
    opts:["loss of electrons","gain of electrons","gain of protons","loss of neutrons"], correct:0,
    steps:`Remember OIL RIG: Oxidation Is Loss of electrons, Reduction Is Gain of electrons.<br><span class="final">Answer: loss of electrons</span>` },
  { topic:"Redox & Electrolysis", ref:"KPC Chemistry - Redox & Electrolysis", product:"chemistry-redox",
    difficulty:"standard", type:"text",
    q:"When molten lead bromide is electrolysed, name the metal formed at the negative electrode (cathode). (one word)",
    data:"Type your answer (a word).", accept:["lead"],
    steps:`Positive metal ions (Pb2+) are attracted to the negative electrode, where they gain electrons and form <b>lead</b> metal.<br><span class="final">Answer: Lead</span>` },
  { topic:"Redox & Electrolysis", ref:"KPC Chemistry - Redox & Electrolysis", product:"chemistry-redox",
    difficulty:"standard", type:"mcq",
    q:"In electrolysis, towards which electrode do the positive ions (cations) move?",
    opts:["the positive electrode (anode)","the negative electrode (cathode)","neither electrode","both equally"], correct:1,
    steps:`Opposite charges attract, so positive cations move to the <b>negative electrode (cathode)</b>.<br><span class="final">Answer: the negative electrode (cathode)</span>` },
  { topic:"Redox & Electrolysis", ref:"KPC Chemistry - Redox & Electrolysis", product:"chemistry-redox",
    difficulty:"hard", type:"mcq",
    q:"When concentrated aqueous sodium chloride (brine) is electrolysed, which gas is given off at the positive electrode (anode)?",
    opts:["hydrogen","oxygen","chlorine","sodium"], correct:2,
    steps:`At the anode in concentrated brine, chloride ions are discharged to give <b>chlorine</b> gas. (Hydrogen forms at the cathode.)<br><span class="final">Answer: chlorine</span>` },

  /* T8 Metals & Reactivity */
  { topic:"Metals & Reactivity", ref:"KPC Chemistry - Metals & Reactivity", product:"chemistry-metals",
    difficulty:"foundation", type:"mcq",
    q:"Which of these metals is the MOST reactive?",
    opts:["potassium","iron","copper","gold"], correct:0,
    steps:`In the reactivity series, potassium is near the top (very reactive); gold is at the bottom (very unreactive).<br><span class="final">Answer: potassium</span>` },
  { topic:"Metals & Reactivity", ref:"KPC Chemistry - Metals & Reactivity", product:"chemistry-metals",
    difficulty:"standard", type:"mcq",
    q:"A more reactive metal displaces a less reactive metal from its salt solution. Which mixture will react?",
    opts:["copper added to magnesium sulfate solution","magnesium added to copper sulfate solution","gold added to iron sulfate solution","copper added to iron sulfate solution"], correct:1,
    steps:`Magnesium is more reactive than copper, so it displaces copper from copper sulfate solution (the blue colour fades and copper is deposited).<br><span class="final">Answer: magnesium added to copper sulfate solution</span>` },
  { topic:"Metals & Reactivity", ref:"KPC Chemistry - Metals & Reactivity", product:"chemistry-metals",
    difficulty:"standard", type:"mcq",
    q:"Iron rusts when it is exposed to which TWO substances?",
    opts:["oxygen and water","nitrogen and oil","carbon dioxide and salt","hydrogen and water"], correct:0,
    steps:`Rusting needs both <b>oxygen and water</b>. Keeping either away (e.g. oiling or painting) prevents rust.<br><span class="final">Answer: oxygen and water</span>` },
  { topic:"Metals & Reactivity", ref:"KPC Chemistry - Metals & Reactivity", product:"chemistry-metals",
    difficulty:"hard", type:"text",
    q:"Iron is extracted from iron oxide in a blast furnace by heating it with carbon, which removes the oxygen. What name is given to a reaction in which oxygen is removed? (one word)",
    data:"Type your answer (a word).", accept:["reduction"],
    steps:`Removing oxygen from a compound is <b>reduction</b>. The iron oxide is reduced to iron; the carbon is oxidised.<br><span class="final">Answer: Reduction</span>` },

  /* T9 Organic Chemistry */
  { topic:"Organic Chemistry", ref:"KPC Chemistry - Organic Chemistry", product:"chemistry-organic",
    difficulty:"foundation", type:"mcq",
    q:"Compounds that contain only the elements hydrogen and carbon are called...",
    opts:["carbohydrates","hydrocarbons","alcohols","salts"], correct:1,
    steps:`Compounds of only hydrogen and carbon are <b>hydrocarbons</b> (for example the alkanes and alkenes).<br><span class="final">Answer: hydrocarbons</span>` },
  { topic:"Organic Chemistry", ref:"KPC Chemistry - Organic Chemistry", product:"chemistry-organic",
    difficulty:"standard", type:"work",
    q:"Alkanes have the general formula CnH(2n+2). How many hydrogen atoms are in the alkane with 3 carbon atoms (propane)?",
    data:"Give a whole number.", accept:[8], unit:"",
    steps:`H atoms = 2n + 2 = (2 x 3) + 2 = 6 + 2<br><span class="final">= 8 hydrogen atoms (C3H8)</span>` },
  { topic:"Organic Chemistry", ref:"KPC Chemistry - Organic Chemistry", product:"chemistry-organic",
    difficulty:"standard", type:"mcq",
    q:"How can you tell an alkene apart from an alkane using bromine water? The alkene...",
    opts:["turns bromine water blue","decolourises bromine water (orange to colourless)","has no effect on bromine water","sets bromine water on fire"], correct:1,
    steps:`Alkenes are unsaturated (they have a C=C double bond), so they <b>decolourise</b> bromine water from orange to colourless. Alkanes do not.<br><span class="final">Answer: decolourises bromine water</span>` },
  { topic:"Organic Chemistry", ref:"KPC Chemistry - Organic Chemistry", product:"chemistry-organic",
    difficulty:"hard", type:"mcq",
    q:"Many small alkene molecules (monomers) join together to make a very long molecule such as poly(ethene). What is this process called?",
    opts:["cracking","polymerisation","fermentation","distillation"], correct:1,
    steps:`Joining many monomers into a long chain is <b>polymerisation</b> (addition polymerisation for alkenes).<br><span class="final">Answer: polymerisation</span>` },

  /* T10 Air, Water, Earth & Analysis */
  { topic:"Air, Water, Earth & Analysis", ref:"KPC Chemistry - Air, Water, Earth & Analysis", product:"chemistry-environment",
    difficulty:"foundation", type:"mcq",
    q:"Approximately what percentage of clean, dry air is nitrogen?",
    opts:["about 21%","about 78%","about 0.04%","about 50%"], correct:1,
    steps:`Air is roughly <b>78% nitrogen</b> and about 21% oxygen, with small amounts of other gases (including 0.04% carbon dioxide).<br><span class="final">Answer: about 78%</span>` },
  { topic:"Air, Water, Earth & Analysis", ref:"KPC Chemistry - Air, Water, Earth & Analysis", product:"chemistry-environment",
    difficulty:"standard", type:"mcq",
    q:"In Malta, much drinking water is produced by removing the salt from sea water. What is this process called?",
    opts:["desalination (reverse osmosis)","chlorination only","simple filtration","fermentation"], correct:0,
    steps:`Removing salt from sea water to make fresh water is <b>desalination</b>, often done by reverse osmosis. It is a major source of Malta's drinking water.<br><span class="final">Answer: desalination (reverse osmosis)</span>` },
  { topic:"Air, Water, Earth & Analysis", ref:"KPC Chemistry - Air, Water, Earth & Analysis", product:"chemistry-environment",
    difficulty:"standard", type:"text",
    q:"A colourless gas turns limewater milky (cloudy). Name this gas. (two words)",
    data:"Type your answer (two words).", accept:["carbon dioxide","co2"],
    steps:`The gas that turns limewater milky is <b>carbon dioxide</b>. This is the standard test for CO2.<br><span class="final">Answer: Carbon dioxide</span>` },
  { topic:"Air, Water, Earth & Analysis", ref:"KPC Chemistry - Air, Water, Earth & Analysis", product:"chemistry-environment",
    difficulty:"hard", type:"mcq",
    q:"To test a solution for the sulfate ion, you add dilute acid and then barium chloride solution. A positive result is...",
    opts:["a white precipitate","a yellow precipitate","a brown gas","a blue solution"], correct:0,
    steps:`Sulfate ions give a <b>white precipitate</b> of barium sulfate with acidified barium chloride.<br><span class="final">Answer: a white precipitate</span>` },
];

const WHY = {
  "Atomic Structure & Periodic Table":"Revise protons/neutrons/electrons, electron shells and group/period trends.",
  "Bonding & Structure":"Review ionic, covalent and metallic bonding and how structure explains properties.",
  "The Mole & Stoichiometry":"Practise relative formula mass, moles = mass/Mr and reacting-mass calculations.",
  "Acids, Bases & Salts":"Revise pH and indicators, neutralisation, salt preparation and titration calculations.",
  "Rates of Reaction":"Review the factors affecting rate and explaining them by collision theory.",
  "Energetics":"Practise exothermic vs endothermic, energy-level ideas and Q = mc(change in temp).",
  "Redox & Electrolysis":"Revise oxidation and reduction (OIL RIG) and the products of electrolysis.",
  "Metals & Reactivity":"Review the reactivity series, displacement, rusting and metal extraction.",
  "Organic Chemistry":"Revise hydrocarbons, alkanes/alkenes, the bromine-water test and polymerisation.",
  "Air, Water, Earth & Analysis":"Review the composition of air, water treatment, pollutants and the chemical tests."
};

const CFG = { SUBJECT, TOPIC_ORDER, QUESTIONS, WHY };
export function publicQuestions() { return pub(CFG); }
export function gradeAndReport(name, answers, env) { return grade(CFG, name, answers, env); }
