/* =========================================================================
   KPC Diagnostic - MATHEMATICS Question Bank (SERVER SIDE ONLY)
   SEC / MATSEC O-Level Mathematics. 10 topics x 4 = 40 (1 foundation,
   2 standard, 1 hard each). Overwhelmingly numeric single-answer questions
   (euro/money contexts where natural) with a couple of concept MCQs.
   Numeric answers use a tolerance, so sensible rounding still marks correct.
   Original SEC-style content; publicQuestions() hides answers.
   ========================================================================= */
import { publicQuestions as pub, gradeAndReport as grade } from "./_grade.js";

export const SUBJECT = "Mathematics";

export const TOPIC_ORDER = [
  "Number & Standard Form",
  "Fractions, Decimals & Percentages",
  "Money & Percentages",
  "Ratio & Proportion",
  "Algebra",
  "Equations & Sequences",
  "Area, Perimeter & Volume",
  "Pythagoras & Trigonometry",
  "Angles & Geometry",
  "Statistics & Probability"
];

export const QUESTIONS = [
  /* T1 Number & Standard Form */
  { topic:"Number & Standard Form", ref:"KPC Maths - Number & Standard Form", product:"maths-number",
    difficulty:"foundation", type:"work",
    q:"Work out 7 + 3 x 4 (remember the order of operations).",
    data:"Give a number.", accept:[19], unit:"",
    steps:`Do multiplication first: 3 x 4 = 12. Then 7 + 12<br><span class="final">= 19</span>` },
  { topic:"Number & Standard Form", ref:"KPC Maths - Number & Standard Form", product:"maths-number",
    difficulty:"standard", type:"work",
    q:"Write 3.2 x 10^4 as an ordinary number.",
    data:"Give a number.", accept:[32000], unit:"",
    steps:`3.2 x 10^4 means 3.2 x 10000<br><span class="final">= 32000</span>` },
  { topic:"Number & Standard Form", ref:"KPC Maths - Number & Standard Form", product:"maths-number",
    difficulty:"standard", type:"work",
    q:"Round 3.857 to 1 decimal place.",
    data:"Give a number.", accept:[3.9], unit:"",
    steps:`The second decimal digit is 5, so round the first decimal up: 3.8 -> <b>3.9</b>.<br><span class="final">= 3.9</span>` },
  { topic:"Number & Standard Form", ref:"KPC Maths - Number & Standard Form", product:"maths-number",
    difficulty:"hard", type:"work",
    q:"Work out (2.5 x 10^3) x (4 x 10^2). Give your answer as an ordinary number.",
    data:"Give a number.", accept:[1000000], unit:"",
    steps:`2.5 x 10^3 = 2500 and 4 x 10^2 = 400. Then 2500 x 400<br><span class="final">= 1 000 000</span>` },

  /* T2 Fractions, Decimals & Percentages */
  { topic:"Fractions, Decimals & Percentages", ref:"KPC Maths - Fractions, Decimals & Percentages", product:"maths-fractions",
    difficulty:"foundation", type:"work",
    q:"Write 1/4 as a decimal.",
    data:"Give a decimal.", accept:[0.25], unit:"",
    steps:`1 / 4 = 1 divided by 4<br><span class="final">= 0.25</span>` },
  { topic:"Fractions, Decimals & Percentages", ref:"KPC Maths - Fractions, Decimals & Percentages", product:"maths-fractions",
    difficulty:"standard", type:"work",
    q:"Work out 25% of 80.",
    data:"Give a number.", accept:[20], unit:"",
    steps:`25% = 1/4, so 80 / 4<br><span class="final">= 20</span>` },
  { topic:"Fractions, Decimals & Percentages", ref:"KPC Maths - Fractions, Decimals & Percentages", product:"maths-fractions",
    difficulty:"standard", type:"work",
    q:"Work out 3/5 of 200.",
    data:"Give a number.", accept:[120], unit:"",
    steps:`200 / 5 = 40, then 40 x 3<br><span class="final">= 120</span>` },
  { topic:"Fractions, Decimals & Percentages", ref:"KPC Maths - Fractions, Decimals & Percentages", product:"maths-fractions",
    difficulty:"hard", type:"work",
    q:"Increase 60 by 15%.",
    data:"Give a number.", accept:[69], unit:"",
    steps:`15% of 60 = 0.15 x 60 = 9. Then 60 + 9<br><span class="final">= 69</span> (or 60 x 1.15)` },

  /* T3 Money & Percentages */
  { topic:"Money & Percentages", ref:"KPC Maths - Money & Percentages", product:"maths-money",
    difficulty:"foundation", type:"work",
    q:"A shirt costs 40 euro. In a sale it is reduced by 10%. What is the sale price?",
    data:"Give your answer in euro.", accept:[36], unit:"€",
    steps:`10% of 40 = 4, so the reduction is 4 euro. Sale price = 40 - 4<br><span class="final">= 36 euro</span>` },
  { topic:"Money & Percentages", ref:"KPC Maths - Money & Percentages", product:"maths-money",
    difficulty:"standard", type:"work",
    q:"A shop buys a bag for 20 euro and sells it for 25 euro. Calculate the percentage profit.",
    data:"Give your answer as a percentage.", accept:[25], unit:"%",
    steps:`profit = 25 - 20 = 5 euro. percentage profit = (profit / cost) x 100 = (5 / 20) x 100<br><span class="final">= 25%</span>` },
  { topic:"Money & Percentages", ref:"KPC Maths - Money & Percentages", product:"maths-money",
    difficulty:"standard", type:"work",
    q:"500 euro is invested at 4% simple interest per year. How much interest is earned in 3 years?",
    data:"Give your answer in euro.", accept:[60], unit:"€",
    steps:`interest per year = 4% of 500 = 20 euro. Over 3 years: 20 x 3<br><span class="final">= 60 euro</span>` },
  { topic:"Money & Percentages", ref:"KPC Maths - Money & Percentages", product:"maths-money",
    difficulty:"hard", type:"work",
    q:"A car worth 12000 euro loses 10% of its value each year (compound depreciation). What is it worth after 2 years?",
    data:"Give your answer in euro.", accept:[9720], unit:"€",
    steps:`Each year multiply by 0.90.<br>After 1 year: 12000 x 0.9 = 10800. After 2 years: 10800 x 0.9<br><span class="final">= 9720 euro</span>` },

  /* T4 Ratio & Proportion */
  { topic:"Ratio & Proportion", ref:"KPC Maths - Ratio & Proportion", product:"maths-ratio",
    difficulty:"foundation", type:"work",
    q:"40 euro is shared between two people in the ratio 3 : 1. How much does the person with the LARGER share get?",
    data:"Give your answer in euro.", accept:[30], unit:"€",
    steps:`Total parts = 3 + 1 = 4, so one part = 40 / 4 = 10 euro. Larger share = 3 parts = 3 x 10<br><span class="final">= 30 euro</span>` },
  { topic:"Ratio & Proportion", ref:"KPC Maths - Ratio & Proportion", product:"maths-ratio",
    difficulty:"standard", type:"work",
    q:"A recipe for 4 people needs 200 g of flour. How much flour is needed for 6 people?",
    data:"Give your answer in grams (g).", accept:[300], unit:"g",
    steps:`Flour per person = 200 / 4 = 50 g. For 6 people: 50 x 6<br><span class="final">= 300 g</span>` },
  { topic:"Ratio & Proportion", ref:"KPC Maths - Ratio & Proportion", product:"maths-ratio",
    difficulty:"standard", type:"work",
    q:"8 identical pens cost 6 euro. How much do 20 of the same pens cost?",
    data:"Give your answer in euro.", accept:[15], unit:"€",
    steps:`Cost of one pen = 6 / 8 = 0.75 euro. For 20 pens: 0.75 x 20<br><span class="final">= 15 euro</span>` },
  { topic:"Ratio & Proportion", ref:"KPC Maths - Ratio & Proportion", product:"maths-ratio",
    difficulty:"hard", type:"work",
    q:"5 workers build a wall in 12 days. Working at the same rate, how many days would 3 workers take? (inverse proportion)",
    data:"Give your answer in days.", accept:[20], unit:"days",
    steps:`Total work = 5 x 12 = 60 worker-days. With 3 workers: 60 / 3<br><span class="final">= 20 days</span>` },

  /* T5 Algebra */
  { topic:"Algebra", ref:"KPC Maths - Algebra", product:"maths-algebra",
    difficulty:"foundation", type:"work",
    q:"If x = 5, work out the value of 3x + 2.",
    data:"Give a number.", accept:[17], unit:"",
    steps:`3x + 2 = (3 x 5) + 2 = 15 + 2<br><span class="final">= 17</span>` },
  { topic:"Algebra", ref:"KPC Maths - Algebra", product:"maths-algebra",
    difficulty:"standard", type:"mcq",
    q:"Which is the correct factorisation of x^2 + 5x + 6?",
    opts:["(x + 1)(x + 6)","(x + 2)(x + 3)","(x + 5)(x + 1)","(x + 2)(x + 4)"], correct:1,
    steps:`We need two numbers that multiply to 6 and add to 5: those are 2 and 3.<br><span class="final">Answer: (x + 2)(x + 3)</span>` },
  { topic:"Algebra", ref:"KPC Maths - Algebra", product:"maths-algebra",
    difficulty:"standard", type:"work",
    q:"Solve 5x - 3 = 2x + 9. What is the value of x?",
    data:"Give a number.", accept:[4], unit:"",
    steps:`5x - 2x = 9 + 3 -> 3x = 12 -> x = 12 / 3<br><span class="final">x = 4</span>` },
  { topic:"Algebra", ref:"KPC Maths - Algebra", product:"maths-algebra",
    difficulty:"hard", type:"work",
    q:"The equation x^2 + 5x + 6 = 0 factorises to (x + 2)(x + 3) = 0. One solution is x = -2. What is the OTHER solution?",
    data:"Give a number.", accept:[-3], unit:"",
    steps:`Setting (x + 3) = 0 gives x = -3.<br><span class="final">The other solution is x = -3</span>` },

  /* T6 Equations & Sequences */
  { topic:"Equations & Sequences", ref:"KPC Maths - Equations & Sequences", product:"maths-sequences",
    difficulty:"foundation", type:"work",
    q:"Here is a sequence: 3, 7, 11, 15, ... What is the next term?",
    data:"Give a number.", accept:[19], unit:"",
    steps:`The pattern adds 4 each time: 15 + 4<br><span class="final">= 19</span>` },
  { topic:"Equations & Sequences", ref:"KPC Maths - Equations & Sequences", product:"maths-sequences",
    difficulty:"standard", type:"work",
    q:"The nth term of a sequence is 4n - 1. What is the 10th term?",
    data:"Give a number.", accept:[39], unit:"",
    steps:`Substitute n = 10: (4 x 10) - 1 = 40 - 1<br><span class="final">= 39</span>` },
  { topic:"Equations & Sequences", ref:"KPC Maths - Equations & Sequences", product:"maths-sequences",
    difficulty:"standard", type:"work",
    q:"Solve the simultaneous equations x + y = 10 and x - y = 4. What is the value of x?",
    data:"Give a number.", accept:[7], unit:"",
    steps:`Add the equations: (x + y) + (x - y) = 10 + 4 -> 2x = 14 -> x = 7.<br><span class="final">x = 7</span>` },
  { topic:"Equations & Sequences", ref:"KPC Maths - Equations & Sequences", product:"maths-sequences",
    difficulty:"hard", type:"work",
    q:"The nth term of a sequence is n^2 + 2. What is the 5th term?",
    data:"Give a number.", accept:[27], unit:"",
    steps:`Substitute n = 5: 5^2 + 2 = 25 + 2<br><span class="final">= 27</span>` },

  /* T7 Area, Perimeter & Volume */
  { topic:"Area, Perimeter & Volume", ref:"KPC Maths - Area, Perimeter & Volume", product:"maths-mensuration",
    difficulty:"foundation", type:"work",
    q:"A rectangle is 8 cm long and 5 cm wide. What is its area?",
    data:"Give your answer in cm^2.", accept:[40], unit:"cm²",
    steps:`Area of a rectangle = length x width = 8 x 5<br><span class="final">= 40 cm2</span>` },
  { topic:"Area, Perimeter & Volume", ref:"KPC Maths - Area, Perimeter & Volume", product:"maths-mensuration",
    difficulty:"standard", type:"work",
    q:"A triangle has base 10 cm and height 6 cm. What is its area?",
    data:"Give your answer in cm^2.", accept:[30], unit:"cm²",
    steps:`Area of a triangle = 1/2 x base x height = 1/2 x 10 x 6<br><span class="final">= 30 cm2</span>` },
  { topic:"Area, Perimeter & Volume", ref:"KPC Maths - Area, Perimeter & Volume", product:"maths-mensuration",
    difficulty:"standard", type:"work",
    q:"A cube has sides of 4 cm. What is its volume?",
    data:"Give your answer in cm^3.", accept:[64], unit:"cm³",
    steps:`Volume of a cube = side x side x side = 4 x 4 x 4<br><span class="final">= 64 cm3</span>` },
  { topic:"Area, Perimeter & Volume", ref:"KPC Maths - Area, Perimeter & Volume", product:"maths-mensuration",
    difficulty:"hard", type:"work",
    q:"A circle has radius 7 cm. Work out its area, using pi = 3.14. Give your answer to the nearest whole number.",
    data:"Give your answer in cm^2.", accept:[154, 153.86], unit:"cm²",
    steps:`Area = pi x r^2 = 3.14 x 7^2 = 3.14 x 49 = 153.86<br><span class="final">= 154 cm2 (to the nearest whole number)</span>` },

  /* T8 Pythagoras & Trigonometry */
  { topic:"Pythagoras & Trigonometry", ref:"KPC Maths - Pythagoras & Trigonometry", product:"maths-trig",
    difficulty:"foundation", type:"work",
    q:"A right-angled triangle has its two shorter sides 3 cm and 4 cm. Work out the length of the hypotenuse.",
    data:"Give your answer in cm.", accept:[5], unit:"cm",
    steps:`Pythagoras: hypotenuse^2 = 3^2 + 4^2 = 9 + 16 = 25, so hypotenuse = root 25<br><span class="final">= 5 cm</span>` },
  { topic:"Pythagoras & Trigonometry", ref:"KPC Maths - Pythagoras & Trigonometry", product:"maths-trig",
    difficulty:"standard", type:"work",
    q:"A right-angled triangle has hypotenuse 13 cm and one shorter side 5 cm. Work out the other shorter side.",
    data:"Give your answer in cm.", accept:[12], unit:"cm",
    steps:`other side^2 = 13^2 - 5^2 = 169 - 25 = 144, so the side = root 144<br><span class="final">= 12 cm</span>` },
  { topic:"Pythagoras & Trigonometry", ref:"KPC Maths - Pythagoras & Trigonometry", product:"maths-trig",
    difficulty:"standard", type:"work",
    q:"In a right-angled triangle, the side opposite an angle is 6 cm and the hypotenuse is 12 cm. Work out the angle using sine.",
    data:"Give your answer in degrees.", accept:[30], unit:"°",
    steps:`sin(angle) = opposite / hypotenuse = 6 / 12 = 0.5, so angle = inverse sin of 0.5<br><span class="final">= 30 degrees</span>` },
  { topic:"Pythagoras & Trigonometry", ref:"KPC Maths - Pythagoras & Trigonometry", product:"maths-trig",
    difficulty:"hard", type:"work",
    q:"A ladder 10 m long leans against a wall. The foot of the ladder is 6 m from the base of the wall. How high up the wall does the ladder reach?",
    data:"Give your answer in metres (m).", accept:[8], unit:"m",
    steps:`height^2 = 10^2 - 6^2 = 100 - 36 = 64, so height = root 64<br><span class="final">= 8 m</span>` },

  /* T9 Angles & Geometry */
  { topic:"Angles & Geometry", ref:"KPC Maths - Angles & Geometry", product:"maths-geometry",
    difficulty:"foundation", type:"work",
    q:"The angles in a triangle add up to 180 degrees. Two of the angles are 50 degrees and 60 degrees. What is the third angle?",
    data:"Give your answer in degrees.", accept:[70], unit:"°",
    steps:`Third angle = 180 - 50 - 60<br><span class="final">= 70 degrees</span>` },
  { topic:"Angles & Geometry", ref:"KPC Maths - Angles & Geometry", product:"maths-geometry",
    difficulty:"standard", type:"work",
    q:"Angles on a straight line add up to 180 degrees. One angle is 115 degrees. What is the other angle?",
    data:"Give your answer in degrees.", accept:[65], unit:"°",
    steps:`Other angle = 180 - 115<br><span class="final">= 65 degrees</span>` },
  { topic:"Angles & Geometry", ref:"KPC Maths - Angles & Geometry", product:"maths-geometry",
    difficulty:"standard", type:"mcq",
    q:"The angle in a semicircle (the angle made at the circumference by a diameter) is always...",
    opts:["45 degrees","60 degrees","90 degrees","180 degrees"], correct:2,
    steps:`The angle in a semicircle is always a right angle, <b>90 degrees</b> (a circle theorem).<br><span class="final">Answer: 90 degrees</span>` },
  { topic:"Angles & Geometry", ref:"KPC Maths - Angles & Geometry", product:"maths-geometry",
    difficulty:"hard", type:"work",
    q:"A regular hexagon has 6 equal sides. Work out the size of each interior angle. (interior angle = (n - 2) x 180 / n)",
    data:"Give your answer in degrees.", accept:[120], unit:"°",
    steps:`(n - 2) x 180 / n = (6 - 2) x 180 / 6 = 4 x 180 / 6 = 720 / 6<br><span class="final">= 120 degrees</span>` },

  /* T10 Statistics & Probability */
  { topic:"Statistics & Probability", ref:"KPC Maths - Statistics & Probability", product:"maths-statistics",
    difficulty:"foundation", type:"work",
    q:"Find the mean (average) of these numbers: 4, 6, 8, 10.",
    data:"Give a number.", accept:[7], unit:"",
    steps:`mean = total / how many = (4 + 6 + 8 + 10) / 4 = 28 / 4<br><span class="final">= 7</span>` },
  { topic:"Statistics & Probability", ref:"KPC Maths - Statistics & Probability", product:"maths-statistics",
    difficulty:"standard", type:"work",
    q:"Find the median of these numbers: 3, 7, 2, 9, 5. (Put them in order first.)",
    data:"Give a number.", accept:[5], unit:"",
    steps:`In order: 2, 3, 5, 7, 9. The middle value is<br><span class="final">5</span>` },
  { topic:"Statistics & Probability", ref:"KPC Maths - Statistics & Probability", product:"maths-statistics",
    difficulty:"standard", type:"work",
    q:"A bag holds 3 red balls and 5 blue balls. What is the probability of picking a red ball at random? Give your answer as a decimal to 3 decimal places.",
    data:"Give a decimal.", accept:[0.375], unit:"",
    steps:`P(red) = number of red / total = 3 / 8<br><span class="final">= 0.375</span>` },
  { topic:"Statistics & Probability", ref:"KPC Maths - Statistics & Probability", product:"maths-statistics",
    difficulty:"hard", type:"work",
    q:"The mean of four numbers is 10. Three of the numbers are 8, 9 and 12. What is the fourth number?",
    data:"Give a number.", accept:[11], unit:"",
    steps:`Total of the four numbers = mean x how many = 10 x 4 = 40.<br>The three known numbers add to 8 + 9 + 12 = 29.<br>Fourth number = 40 - 29<br><span class="final">= 11</span>` },
];

const WHY = {
  "Number & Standard Form":"Revise order of operations, rounding and standard form (powers of ten).",
  "Fractions, Decimals & Percentages":"Practise converting between fractions, decimals and percentages and finding percentages of amounts.",
  "Money & Percentages":"Review profit and loss, simple and compound interest and depreciation.",
  "Ratio & Proportion":"Practise sharing in a ratio, recipe scaling and direct and inverse proportion.",
  "Algebra":"Revise substituting, expanding, factorising and solving linear equations.",
  "Equations & Sequences":"Practise simultaneous equations, the nth term and continuing sequences.",
  "Area, Perimeter & Volume":"Review areas of rectangles, triangles and circles and volumes of solids.",
  "Pythagoras & Trigonometry":"Practise Pythagoras' theorem and using sine, cosine and tangent.",
  "Angles & Geometry":"Revise angle facts, angles in polygons and the circle theorems.",
  "Statistics & Probability":"Practise mean, median, mode and range, and simple probability."
};

const CFG = { SUBJECT, TOPIC_ORDER, QUESTIONS, WHY };
export function publicQuestions() { return pub(CFG); }
export function gradeAndReport(name, answers, env) { return grade(CFG, name, answers, env); }
